CREATE TABLE person_info (
    PID VARCHAR(32) NOT NULL,
    name VARCHAR(32) UNIQUE NOT NULL,
    hashed_password INT NOT NULL,
    activated BOOLEAN NOT NULL,
    facial_vector DOUBLE PRECISION,

    PRIMARY KEY (PID)
);

CREATE TABLE session_info (
    SID CHAR(32) NOT NULL AUTO_INCREMENT,
    creator VARCHAR(64),
    session_name VARCHAR(512),
    venue VARCHAR(512),
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    next_session CHAR(32),

    CHECK (start_time < end_time),
    PRIMARY KEY(SID),
    FOREIGN KEY(next_session) REFERENCES session_info(SID)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE attendance (
    AID CHAR(32) NOT NULL AUTO_INCREMENT,
    PID VARCHAR(32) NOT NULL,
    SID CHAR(32) NOT NULL,

    check_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    checkIn BOOLEAN,

    PRIMARY KEY (AID),
    FOREIGN KEY (PID) REFERENCES person_info(PID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (SID) REFERENCES session_info(SID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE authorized_attendee (
    PID VARCHAR(32) NOT NULL,
    SID CHAR(32) NOT NULL,

    PRIMARY KEY(PID, SID),
    FOREIGN KEY (PID) REFERENCES person_info(PID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (SID) REFERENCES session_info(SID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

